repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-added-large-files
    args: ['--maxkb=500']
  - id: check-executables-have-shebangs
  - id: pretty-format-json
    args: ['--autofix', '--no-sort-keys', '--indent=4']
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: detect-private-key
  - id: check-merge-conflict
  - id: detect-aws-credentials
    args: ['--allow-missing-credentials']
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.21.0
  hooks:
  - id: terraform_fmt
  - id: terraform_docs
- repo: git://github.com/smian/pre-commit-makefile
  rev: 261f8fb4b31dfdc05d1a1d7fbde1f1462ecde66d
  hooks:
  - id: makefile-doc
